/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 20 22:35:49 GMT 2021
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jsoup.helper.CookieUtil;
import org.jsoup.helper.HttpConnection;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CookieUtil_ESTest extends CookieUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Request httpConnection_Request1 = new HttpConnection.Request(httpConnection_Request0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      hashMap0.put("0A&O5Kz29!I;k]-@-", "0A&O5Kz29!I;k]-@-");
      httpConnection_Request1.cookies = (Map<String, String>) hashMap0;
      HttpURLConnection httpURLConnection0 = mock(HttpURLConnection.class, new ViolatedAssumptionAnswer());
      CookieUtil.applyCookiesToRequest(httpConnection_Request1, httpURLConnection0);
      assertFalse(httpConnection_Request1.ignoreContentType());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      CookieUtil.applyCookiesToRequest(httpConnection_Request0, (HttpURLConnection) null);
      assertFalse(httpConnection_Request0.ignoreContentType());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URL uRL0 = MockURL.getFileExample();
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      CookieUtil.storeCookies(httpConnection_Request0, uRL0, hashMap0);
      assertNull(httpConnection_Request0.requestBody());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CookieUtil cookieUtil0 = new CookieUtil();
  }
}
