/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 20 22:34:25 GMT 2021
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.jsoup.SerializationException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SerializationException_ESTest extends SerializationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SerializationException serializationException0 = new SerializationException("");
      Throwable throwable0 = serializationException0.initCause(serializationException0);
      SerializationException serializationException1 = new SerializationException(throwable0);
      assertFalse(serializationException1.equals((Object)serializationException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SerializationException serializationException0 = new SerializationException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("CY3{ ^vym@:_!;&M.");
      SerializationException serializationException0 = new SerializationException("CY3{ ^vym@:_!;&M.", mockThrowable0);
  }
}
