/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 20 21:34:04 GMT 2021
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Entities;
import org.jsoup.nodes.NodeUtils;
import org.jsoup.nodes.XmlDeclaration;
import org.jsoup.parser.Parser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NodeUtils_ESTest extends NodeUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("org.jsoup.nds.NodeUtils", "org.jsoup.nds.NodeUtils");
      Document document1 = document0.parser((Parser) null);
      Parser parser0 = NodeUtils.parser(document1);
      assertFalse(parser0.isTrackErrors());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DataNode dataNode0 = new DataNode("Os<1m3?n");
      Parser parser0 = NodeUtils.parser(dataNode0);
      assertFalse(parser0.isTrackErrors());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("figcaption", "figcaption");
      Document.OutputSettings document_OutputSettings0 = NodeUtils.outputSettings(document0);
      assertEquals(Entities.EscapeMode.base, document_OutputSettings0.escapeMode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("[C94)", true);
      Document.OutputSettings document_OutputSettings0 = NodeUtils.outputSettings(xmlDeclaration0);
      assertEquals(1, document_OutputSettings0.indentAmount());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Class<Document> class0 = Document.class;
      // Undeclared exception!
      try { 
        NodeUtils.selectXpath("", (Element) null, class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NodeUtils nodeUtils0 = new NodeUtils();
  }
}
